name: bubble
description: A new Flutter project.

version: 0.9+2

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^0.12.0
  http: ^0.12.0+1
  crypto: ^2.0.6
  firebase_admob: ^0.8.0+4
  shared_preferences: ^0.4.2
  date_format: ^1.0.6
  sqflite: ^1.1.0
  url_launcher: ^5.0.2
  vector_math: any

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/appicon.png"
  image_path_ios: "assets/appiconios.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/anchor.png
    - assets/images/arrow.png
    - assets/images/cyan.png
    - assets/images/green.png
    - assets/images/navy.png
    - assets/images/pink.png
    - assets/images/red.png
    - assets/images/yellow.png
    - assets/images/logo.png
    - assets/appicon.png
